// Automatically generated by SUtools, editing not advised.
#ifndef R_FTEST_H
#define R_FTEST_H
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>
#ifdef ENABLE_NLS
#include <libintl.h>
#define _(String) dgettext ("ftest", String)
#else
#define _(String) (String)
#endif

/* New addition */
extern SEXP store_rfun(SEXP rfun);
static const R_CallMethodDef CallEntries[] = {
  {"store_rfun", (DL_FUNC) &store_rfun, 1},
  {NULL, NULL, 0}
};



#define FDEF(name)  {#name, (DL_FUNC) &F77_SUB(name), sizeof(name ## _t)/sizeof(name ## _t[0]), name ##_t}
void F77_SUB(fcallr)(
int *n,
double *y,
double *z,
double *w,
double *res
);
 
static R_NativePrimitiveArgType fcallr_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};

static R_FortranMethodDef fMethods[] = {
FDEF(fcallr) ,
{NULL, NULL, 0}
};

void R_init_ftest(DllInfo *dll){
  R_registerRoutines(dll, NULL, CallEntries, fMethods, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
#endif
